In [1]:
print("Student Performance Analytics System")
print("My EWB Python Project Started Successfully!")

Student Performance Analytics System
My EWB Python Project Started Successfully!

In [2]:
import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

print("Libraries imported successfully!")

Pandas version: 2.2.3
NumPy version: 2.1.3
Libraries imported successfully!

In [3]:
import pandas as pd

data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["Anu", "Ravi", "Priya", "Kiran", "Sneha"],
    "Department": ["AIML", "CSE", "AIML", "ECE", "CSE"],
    "Python": [85, 72, 90, 65, 78],
    "AI": [88, 68, 95, 70, 82],
    "Maths": [80, 75, 92, 60, 85],
    "Attendance": [92, 85, 98, 72, 90]
}

df = pd.DataFrame(data)

display(df)

   Student_ID   Name Department  Python  AI  Maths  Attendance
0         101    Anu       AIML      85  88     80          92
1         102   Ravi        CSE      72  68     75          85
2         103  Priya       AIML      90  95     92          98
3         104  Kiran        ECE      65  70     60          72
4         105  Sneha        CSE      78  82     85          90

In [4]:
data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["Anu", "Ravi", "Priya", "Kiran", "Sneha"],
    "Department": ["AIML", "CSE", "AIML", "ECE", "CSE"],
    "Python": [85, 72, 90, 65, 78],
    "AI": [88, 68, 95, 70, 82],
    "Maths": [80, 75, 92, 60, 85],
    "Attendance": [92, 85, 98, 72, 90]
}

df = pd.DataFrame(data)

display(df)

   Student_ID   Name Department  Python  AI  Maths  Attendance
0         101    Anu       AIML      85  88     80          92
1         102   Ravi        CSE      72  68     75          85
2         103  Priya       AIML      90  95     92          98
3         104  Kiran        ECE      65  70     60          72
4         105  Sneha        CSE      78  82     85          90

In [5]:
print(df.columns.tolist())

['Student_ID', 'Name', 'Department', 'Python', 'AI', 'Maths', 'Attendance']

In [6]:
print(df.iloc[0])

Student_ID     101
Name           Anu
Department    AIML
Python          85
AI              88
Maths           80
Attendance      92
Name: 0, dtype: object

In [7]:
df["Total_Marks"] = df["Python"] + df["AI"] + df["Maths"]

display(df)

   Student_ID   Name Department  Python  AI  Maths  Attendance  Total_Marks
0         101    Anu       AIML      85  88     80          92          253
1         102   Ravi        CSE      72  68     75          85          215
2         103  Priya       AIML      90  95     92          98          277
3         104  Kiran        ECE      65  70     60          72          195
4         105  Sneha        CSE      78  82     85          90          245

In [8]:
df["Average_Marks"] = df["Total_Marks"] / 3

display(df[["Name", "Total_Marks", "Average_Marks"]])

    Name  Total_Marks  Average_Marks
0    Anu          253      84.333333
1   Ravi          215      71.666667
2  Priya          277      92.333333
3  Kiran          195      65.000000
4  Sneha          245      81.666667

In [9]:
def assign_grade(avg):
    if avg >= 90:
        return "A"
    elif avg >= 80:
        return "B"
    elif avg >= 70:
        return "C"
    elif avg >= 60:
        return "D"
    else:
        return "F"

df["Grade"] = df["Average_Marks"].apply(assign_grade)

display(df[["Name", "Average_Marks", "Grade"]])

    Name  Average_Marks Grade
0    Anu      84.333333     B
1   Ravi      71.666667     C
2  Priya      92.333333     A
3  Kiran      65.000000     D
4  Sneha      81.666667     B

In [10]:
def check_result(avg):
    if avg >= 40:
        return "Pass"
    else:
        return "Fail"

df["Result"] = df["Average_Marks"].apply(check_result)

display(df[["Name", "Average_Marks", "Grade", "Result"]])

    Name  Average_Marks Grade Result
0    Anu      84.333333     B   Pass
1   Ravi      71.666667     C   Pass
2  Priya      92.333333     A   Pass
3  Kiran      65.000000     D   Pass
4  Sneha      81.666667     B   Pass

In [11]:
print("Highest Average:", df["Average_Marks"].max())

print("Lowest Average:", df["Average_Marks"].min())

print("Class Average:", df["Average_Marks"].mean())

Highest Average: 92.33333333333333
Lowest Average: 65.0
Class Average: 79.0

In [12]:
subjects = ["Python", "AI", "Maths"]

for subject in subjects:
    print(subject, "Average:", df[subject].mean())

Python Average: 78.0
AI Average: 80.6
Maths Average: 78.4

In [13]:
top_students = df.sort_values(
    by="Average_Marks",
    ascending=False
)

print("Top Performing Students:")
display(
    top_students[
        ["Name", "Average_Marks", "Grade"]
    ].head(3)
)

Top Performing Students:

    Name  Average_Marks Grade
2  Priya      92.333333     A
0    Anu      84.333333     B
4  Sneha      81.666667     B

In [14]:
pass_count = (df["Result"] == "Pass").sum()
fail_count = (df["Result"] == "Fail").sum()

print("Total Students:", len(df))
print("Passed Students:", pass_count)
print("Failed Students:", fail_count)

Total Students: 5
Passed Students: 5
Failed Students: 0

In [15]:
extra_data = {
    "Student_ID": [106, 107, 108, 109, 110,
                   111, 112, 113, 114, 115,
                   116, 117, 118, 119, 120],
    "Name": ["Arjun", "Meena", "Rahul", "Divya", "Karthik",
             "Pooja", "Sai", "Lakshmi", "Varun", "Nisha",
             "Teja", "Kavya", "Rohit", "Harika", "Manoj"],
    "Department": ["CSE", "AIML", "ECE", "CSE", "AIML",
                   "ECE", "CSE", "AIML", "ECE", "CSE",
                   "AIML", "ECE", "CSE", "AIML", "ECE"],
    "Python": [55, 91, 38, 76, 83, 44, 67, 95, 72, 59,
               88, 63, 31, 79, 86],
    "AI": [60, 94, 42, 81, 79, 50, 70, 89, 75, 62,
           92, 68, 35, 84, 90],
    "Maths": [58, 88, 35, 73, 85, 46, 65, 93, 69, 55,
              84, 71, 40, 77, 82],
    "Attendance": [78, 96, 60, 88, 91, 67, 82, 99, 85, 74,
                   94, 80, 55, 87, 92]
}

extra_df = pd.DataFrame(extra_data)

df = pd.concat([df, extra_df], ignore_index=True)

print("Total Students:", len(df))
display(df)

Total Students: 20

,Student_ID,Name,Department,Python,AI,Maths,Attendance,Total_Marks,Average_Marks,Grade,Result
0,101,Anu,AIML,85,88,80,92,253.0,84.333333,B,Pass
1,102,Ravi,CSE,72,68,75,85,215.0,71.666667,C,Pass
2,103,Priya,AIML,90,95,92,98,277.0,92.333333,A,Pass
3,104,Kiran,ECE,65,70,60,72,195.0,65.000000,D,Pass
4,105,Sneha,CSE,78,82,85,90,245.0,81.666667,B,Pass
5,106,Arjun,CSE,55,60,58,78,NaN,NaN,NaN,NaN
6,107,Meena,AIML,91,94,88,96,NaN,NaN,NaN,NaN
7,108,Rahul,ECE,38,42,35,60,NaN,NaN,NaN,NaN
8,109,Divya,CSE,76,81,73,88,NaN,NaN,NaN,NaN
9,110,Karthik,AIML,83,79,85,91,NaN,NaN,NaN,NaN
10,111,Pooja,ECE,44,50,46,67,NaN,NaN,NaN,NaN
11,112,Sai,CSE,67,70,65,82,NaN,NaN,NaN,NaN
12,113,Lakshmi,AIML,95,89,93,99,NaN,NaN,NaN,NaN
13,114,Varun,ECE,72,75,69,85,NaN,NaN,NaN,NaN
14,115,Nisha,CSE,59,62,55,74,NaN,NaN,NaN,NaN
15,116,Teja,AIML,88,92,84,94,NaN,NaN,NaN,NaN
16,117,Kavya,ECE,63,68,71,80,NaN,NaN,NaN,NaN
17,118,Rohit,CSE,31,35,40,55,NaN,NaN,NaN,NaN
18,119,Harika,AIML,79,84,77,87,NaN,NaN,NaN,NaN
19,120,Manoj,ECE,86,90,82,92,NaN,NaN,NaN,NaN

In [16]:
# Calculate total and average marks
subjects = ["Python", "AI", "Maths"]

df["Total_Marks"] = df[subjects].sum(axis=1)
df["Average_Marks"] = df[subjects].mean(axis=1)

# Assign grades
def assign_grade(avg):
    if avg >= 90:
        return "A"
    elif avg >= 80:
        return "B"
    elif avg >= 70:
        return "C"
    elif avg >= 60:
        return "D"
    else:
        return "F"

df["Grade"] = df["Average_Marks"].apply(assign_grade)

# Assign Pass or Fail
def check_result(avg):
    if avg >= 40:
        return "Pass"
    else:
        return "Fail"

df["Result"] = df["Average_Marks"].apply(check_result)

print("Total Students:", len(df))
display(df)

Total Students: 20

,Student_ID,Name,Department,Python,AI,Maths,Attendance,Total_Marks,Average_Marks,Grade,Result
0,101,Anu,AIML,85,88,80,92,253,84.333333,B,Pass
1,102,Ravi,CSE,72,68,75,85,215,71.666667,C,Pass
2,103,Priya,AIML,90,95,92,98,277,92.333333,A,Pass
3,104,Kiran,ECE,65,70,60,72,195,65.000000,D,Pass
4,105,Sneha,CSE,78,82,85,90,245,81.666667,B,Pass
5,106,Arjun,CSE,55,60,58,78,173,57.666667,F,Pass
6,107,Meena,AIML,91,94,88,96,273,91.000000,A,Pass
7,108,Rahul,ECE,38,42,35,60,115,38.333333,F,Fail
8,109,Divya,CSE,76,81,73,88,230,76.666667,C,Pass
9,110,Karthik,AIML,83,79,85,91,247,82.333333,B,Pass
10,111,Pooja,ECE,44,50,46,67,140,46.666667,F,Pass
11,112,Sai,CSE,67,70,65,82,202,67.333333,D,Pass
12,113,Lakshmi,AIML,95,89,93,99,277,92.333333,A,Pass
13,114,Varun,ECE,72,75,69,85,216,72.000000,C,Pass
14,115,Nisha,CSE,59,62,55,74,176,58.666667,F,Pass
15,116,Teja,AIML,88,92,84,94,264,88.000000,B,Pass
16,117,Kavya,ECE,63,68,71,80,202,67.333333,D,Pass
17,118,Rohit,CSE,31,35,40,55,106,35.333333,F,Fail
18,119,Harika,AIML,79,84,77,87,240,80.000000,B,Pass
19,120,Manoj,ECE,86,90,82,92,258,86.000000,B,Pass

In [17]:
# Attendance Analysis

df["Attendance_Status"] = df["Attendance"].apply(
    lambda attendance: "Good Attendance"
    if attendance >= 75
    else "Low Attendance"
)

print("Attendance Analysis:")
display(df[["Name", "Attendance", "Attendance_Status"]])

print("Good Attendance:", (df["Attendance"] >= 75).sum())
print("Low Attendance:", (df["Attendance"] < 75).sum())

Attendance Analysis:

       Name  Attendance Attendance_Status
0       Anu          92   Good Attendance
1      Ravi          85   Good Attendance
2     Priya          98   Good Attendance
3     Kiran          72    Low Attendance
4     Sneha          90   Good Attendance
5     Arjun          78   Good Attendance
6     Meena          96   Good Attendance
7     Rahul          60    Low Attendance
8     Divya          88   Good Attendance
9   Karthik          91   Good Attendance
10    Pooja          67    Low Attendance
11      Sai          82   Good Attendance
12  Lakshmi          99   Good Attendance
13    Varun          85   Good Attendance
14    Nisha          74    Low Attendance
15     Teja          94   Good Attendance
16    Kavya          80   Good Attendance
17    Rohit          55    Low Attendance
18   Harika          87   Good Attendance
19    Manoj          92   Good Attendance

Good Attendance: 15
Low Attendance: 5

In [18]:
# Overall Class Performance Analysis

print("Total Students:", len(df))
print("Class Average Marks:", round(df["Average_Marks"].mean(), 2))
print("Highest Average Marks:", round(df["Average_Marks"].max(), 2))
print("Lowest Average Marks:", round(df["Average_Marks"].min(), 2))

print("Total Passed:", (df["Result"] == "Pass").sum())
print("Total Failed:", (df["Result"] == "Fail").sum())

print("Average Attendance:", round(df["Attendance"].mean(), 2), "%")

Total Students: 20
Class Average Marks: 71.73
Highest Average Marks: 92.33
Lowest Average Marks: 35.33
Total Passed: 18
Total Failed: 2
Average Attendance: 83.25 %

In [19]:
# Department-wise Performance Analysis

department_analysis = df.groupby("Department").agg(
    Total_Students=("Student_ID", "count"),
    Average_Marks=("Average_Marks", "mean"),
    Average_Attendance=("Attendance", "mean")
).round(2)

print("Department-wise Performance:")
display(department_analysis)

Department-wise Performance:

            Total_Students  Average_Marks  Average_Attendance
Department
AIML                     7          87.19               93.86
CSE                      7          64.14               78.86
ECE                      6          62.56               76.00

In [20]:
# Subject-wise Performance Analysis

subjects = ["Python", "AI", "Maths"]

for subject in subjects:
    print(
        subject,
        "Average Marks:",
        round(df[subject].mean(), 2)
    )

Python Average Marks: 70.85
AI Average Marks: 73.7
Maths Average Marks: 70.65

In [21]:
# Display Top 5 Students

top_5_students = df.sort_values(
    by="Average_Marks",
    ascending=False
).head(5)

print("Top 5 Performing Students:")
display(
    top_5_students[
        ["Student_ID", "Name", "Department",
         "Average_Marks", "Grade"]
    ]
)

Top 5 Performing Students:

    Student_ID     Name Department  Average_Marks Grade
2          103    Priya       AIML      92.333333     A
12         113  Lakshmi       AIML      92.333333     A
6          107    Meena       AIML      91.000000     A
15         116     Teja       AIML      88.000000     B
19         120    Manoj        ECE      86.000000     B

In [22]:
# Pass/Fail Summary

result_summary = df["Result"].value_counts()

print("Student Result Summary:")
display(result_summary)

Student Result Summary:

Result
Pass    18
Fail     2
Name: count, dtype: int64

In [23]:
# Export the final dataset to CSV

df.to_csv("Student_Performance_Analytics.csv", index=False)

print("Dataset exported successfully!")

Dataset exported successfully!